name: Publish Images

on:
  push:
    branches: [release-logic]
    tags:
    - 'v*'
    
jobs:

  build-ghcr:
    name: Release to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Log into registry GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/akanieski/ado-agent-orchestrator
        tags: ${{ env.GITHUB_REF_NAME }}
        
    - name: Build and push Docker image to GHCR
      id: build-and-push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64

  build-dockerhub:
    name: Release to Docker Hub Container Registry
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Log into registry GHCR
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: hub.docker.com/akanieski/ado-agent-orchestrator
        tags: ${{ env.GITHUB_REF_NAME }}
        
    - name: Build and push Docker image to GHCR
      id: build-and-push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
